"use client";
import Link from "next/link";
import { FilePanel, LedgerRow } from "@/components/ui/file-panel";
import { Page } from "@/components/ui/page";
import { useAuthStore } from "@/features/auth/store";
import { getDocuments, getEligibility, getMoneySummary, getNotices, getProfileSummary, getThingsToDo } from "@/features/graph/selectors";
import { useCitizenStore } from "@/features/graph/store";
import { IntentComposer } from "@/features/intent/components/intent-composer";
import { useI18n } from "@/i18n/use-i18n";
import { formatCurrency } from "@/lib/format";
function greetingKey() { const h = new Date().getHours(); return h < 12 ? "goodMorning" as const : h < 17 ? "goodAfternoon" as const : "goodEvening" as const; }
export function HomeScreen() { const { t } = useI18n(); const personId = useAuthStore((s) => s.personId); const graph = useCitizenStore((s) => s.graph); if (!personId) return null; const profile = getProfileSummary(graph, personId); if (!profile) return null; const tasks = getThingsToDo(graph, personId); const docs = getDocuments(graph, personId); const benefits = getEligibility(graph, personId).filter((r) => r.status !== "not-eligible"); const unread = getNotices(graph, personId).filter((n) => !n.read); const money = getMoneySummary(graph, personId); return <Page className="grid gap-16 lg:gap-24"><section className="grid min-h-[calc(100svh-6rem)] content-start gap-7 pt-6 lg:min-h-0 lg:pt-14"><p className="text-sm text-ink-mute">{t(greetingKey())}, {profile.person.attrs.name.split(" ")[0]}</p><h1 className="max-w-5xl font-display text-[clamp(4rem,11vw,8.4rem)] font-extrabold leading-[0.78] tracking-[-0.05em] text-ink">{t("needPrompt")}</h1><IntentComposer /></section><div className="grid gap-12 lg:grid-cols-2"><FilePanel label={t("mySnapshot")}><LedgerRow label={t("fullProfile")} value={profile.person.attrs.name} action={<Link className="text-xs underline" href="/you">{t("view")}</Link>} /><LedgerRow label={t("documents")} value={docs.length} action={<Link className="text-xs underline" href="/documents">{t("view")}</Link>} /><LedgerRow label={t("availableBenefits")} value={benefits.length} /><LedgerRow label={t("dueAndRefundable")} value={formatCurrency(money.payable)} /><LedgerRow label={t("unreadNotices")} value={unread.length} /></FilePanel><FilePanel label={t("thingsToDo")}>{tasks.map((task, index) => <LedgerRow action={<Link className="text-xs underline" href={task.href}>{t("view")}</Link>} key={task.id} label={`${String(index + 1).padStart(2, "0")} · ${task.title}`} value={task.meta} />)}</FilePanel></div></Page>; }
